#!/bin/bash
BDEF="\033[00;48m"
BBLK="\033[00;40m"
BRED="\033[00;41m"
BORG="\033[00;47m"
BYEL="\033[00;43m"
BGRN="\033[00;42m"
BBLU="\033[00;44m"
BCYN="\033[00;46m"
BMAG="\033[00;45m"

WHT="\033[01;38m"
BLK="\033[01;30m"
RED="\033[01;31m"
ORG="\033[01;37m"
YEL="\033[01;33m"
GRN="\033[01;32m"
BLU="\033[01;34m"
CYN="\033[01;36m"
MAG="\033[01;35m"

WHT1="\033[10;38m"
BLK1="\033[10;30m"
RED1="\033[10;31m"
ORG1="\033[10;37m"
YEL1="\033[10;33m"
GRN1="\033[10;32m"
BLU1="\033[10;34m"
CYN1="\033[10;36m"
MAG1="\033[10;35m"

LINE=" ${BLK}black  ${RED}red  ${ORG}orange  ${YEL}yellow  ${GRN}green  ${BLU}blue  ${CYN}cyan  ${MAG}magenta "
LINE1=" ${BLK1}black  ${RED1}red  ${ORG1}orange  ${YEL1}yellow  ${GRN1}green  ${BLU1}blue  ${CYN1}cyan  ${MAG1}magenta "

echo -e "$BDEF"
echo -e "     ╔══════════════════════════════════════════════════════════╗"
echo -e " DEF ║$BDEF $LINE1 $BDEF║"
echo -e "     ║$BDEF $LINE $BDEF║"
echo -e "     ╠══════════════════════════════════════════════════════════╣"
echo -e " BLK ║$BBLK $LINE1 $BDEF║"
echo -e "     ║$BBLK $LINE $BDEF║"
echo -e "     ╠══════════════════════════════════════════════════════════╣"
echo -e " RED ║$BRED $LINE1 $BDEF║"
echo -e "     ║$BRED $LINE $BDEF║"
echo -e "     ╠══════════════════════════════════════════════════════════╣"
echo -e " ORG ║$BORG $LINE1 $BDEF║"
echo -e "     ║$BORG $LINE $BDEF║"
echo -e "     ╠══════════════════════════════════════════════════════════╣"
echo -e " YEL ║$BYEL $LINE1 $BDEF║"
echo -e "     ║$BYEL $LINE $BDEF║"
echo -e "     ╠══════════════════════════════════════════════════════════╣"
echo -e " GRN ║$BGRN $LINE1 $BDEF║"
echo -e "     ║$BGRN $LINE $BDEF║"
echo -e "     ╠══════════════════════════════════════════════════════════╣"
echo -e " BLU ║$BBLU $LINE1 $BDEF║"
echo -e "     ║$BBLU $LINE $BDEF║"
echo -e "     ╠══════════════════════════════════════════════════════════╣"
echo -e " CYN ║$BCYN $LINE1 $BDEF║"
echo -e "     ║$BCYN $LINE $BDEF║"
echo -e "     ╠══════════════════════════════════════════════════════════╣"
echo -e " MAG ║$BMAG $LINE1 $BDEF║"
echo -e "     ║$BMAG $LINE $BDEF║"
echo -e "     ╚══════════════════════════════════════════════════════════╝"
